targets = [ "//:container" ]

[[dependency]]
package = "github.com/buckaroo-pm/boost-core"
version = "1.60.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-intrusive"
version = "1.60.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-move"
version = "1.60.0"
