manifest = "5389cd715f566df7a9775b82e9b56afd25996a10895fb3714279b61f49fc4257"

[[dependency]]
package = "github.com/buckaroo-pm/boost-intrusive"
target = "//:intrusive"

[[dependency]]
package = "github.com/buckaroo-pm/boost-move"
target = "//:move"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "branch=master" ]
revision = "f9d6a7b63ef2902777b6078fdebc54e7a57aac03"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "branch=master" ]
revision = "4392ed19b232ed2dde7623843d7e30ef669d860e"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "branch=master" ]
revision = "e8b834a93f7ba935aa63a3d6690804f3bd2b0963"

[lock."github.com/buckaroo-pm/boost-intrusive"]
versions = [ "branch=master" ]
revision = "b78ebe67512688e4402ce97d2ee7e28652da3ff3"

[lock."github.com/buckaroo-pm/boost-move"]
versions = [ "branch=master" ]
revision = "c50bef004827b93d7f60e3c53b8c9c3b54fa0084"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "branch=master" ]
revision = "fdc2df7f811436674a1c55c766b8830a8cd02e96"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "branch=master" ]
revision = "4d0a507c0d1a1011c5a98d57acc9f6b755141e4f"
